export const defaultUser = {
  firstName: "",
  middleName: "",
  lastName: "",
  aboutMe: "",
  gender: "",
  email: "",
  password: "",
  website: "",
  phoneNumber: "",
  education: "",
  streetAddress: "",
  city: "",
  state: "",
  zipCode: "",
  dateOfBirth: "",
  profilePicture: "",
  budgetLimit: 0,
  isLoggedIn: false,
};
